backend:
  name: git-gateway
  branch: main # or master, depending on your GitHub branch name

publish_mode: editorial_workflow

media_folder: "images/uploads" # Folder where uploaded images are stored
public_folder: "/images/uploads" # The same folder, but in the URL path

collections:
  - name: "products" # Name of your collection
    label: "Products" # Name for the UI
    folder: "products" # Folder where your product files will be stored
    create: true # Allow users to create new products
    slug: "{{fields.name}}" # Use the product name to create the filename
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Zazzle Link", name: "zazzleLink", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["halloween", "mobile-cases", "t-shirts", "other-products"]}
