backend:
  name: git-gateway
  branch: main  # or "master" if your repo uses master branch

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Category", name: "category", widget: "select", options: ["T-Shirts", "Hoodies", "Accessories"] }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
